# SITE CONFIGURATION
title: Christopher Williams # your site title
author: GitHub User | cdubbs512 # You :P
description: > # Meta description of Homepage
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/" # the subpath of your site, e.g. /blog
# url: "https://cdubbs512.github.io" # the base hostname & protocol for your site, e.g. http://example.com
url: "https://www.christopherwilliams.us/"

# SEO PLUGIN
social:
  name: Christopher Williams
  links:
    - https://www.linkedin.com/in/christopherwilliams512/
    - https://github.com/cdubbs512

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Posts', link: '/posts'}
  - {name: 'Contact', link: '/contact'}

tagline: >
  Strategic Management Consultant and Financial Leader creating value by clarifying objectives, diving deep into problems, and creating strategic solutions for entrepreneurs, executives and creative visionaries.

hero_img: posts/bcn_marina_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: christopher@christopherwilliams.us # email for form submission

#twitter_username: your_username # replace with your_twitter_username or comment to remove link from footer
linkedin_username: christopherwilliams512 # replace with your_linkedin_username or comment to remove link from footer
github_username:  cdubbs512 # replace with your_github_username or comment to remove link from footer
#instagram_username: your_username # replace with your_instagram_username or comment to remove link from footer

disqus:
  #shortname: cdubbs512 # to enable comments replace with your_disqus_shortname

google_tag_manager: GTM-582CG82 # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
